### ISSUE TITLE
Fix signing with GPG keys on Fedora

### ISSUE THREAD

**Issue by xuthus5** [flathub/com.jetpackduba.Gitnuro#1]
when i configured git to sign commits, i get the error:
```bash
error: gpg failed to sign the data
fatal: failed to write commit object
```
flathub/com.sublimemerge.App#18

**Comment by JetpackDuba** [comment]
Does it happen when running Gitnuro using the JAR version available [here](https://github.com/JetpackDuba/Gitnuro/releases/tag/v1.0.1)? I'm not sure if it's an issue with Gitnuro itself or with flatpak.

**Comment by xuthus5** [comment]
> Does it happen when running Gitnuro using the JAR version available [here](https://github.com/JetpackDuba/Gitnuro/releases/tag/v1.0.1)? I'm not sure if it's an issue with Gitnuro itself or with flatpak.

flatpak, it can not reference host gpg agent.

**Comment by JetpackDuba** [comment]
It's not a flathub specific issue, Gitnuro itself does not implement the logic to sign with GPG. Feel free to open an issue in the app's repository https://github.com/JetpackDuba/Gitnuro
