### ISSUE TITLE
Uses EOL runtime

### ISSUE THREAD

**Issue by k8ieone** [flathub/com.jetpackduba.Gitnuro#18]
```
Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.jetpackduba.Gitnuro
```

**Comment by JetpackDuba** [comment]
Thank you for letting me know.

This week Gitnuro 1.4.0 will be released so I'll take the chance to also update the runtime.

**Comment by k8ieone** [comment]
Awesome, thank you for confirmation.

I have this bad feeling whenever I see a Flatpak using an outdated runtime. Usually it's because the project has been abandoned and I feared this was the case here as well.

Loving your project, keep up the good work :heart:

**Comment by JetpackDuba** [comment]
Verson 1.4.0 with runtime 24.08 has been  merged, it will be available in a few hours :smile_cat:
