### ISSUE TITLE
flatpak build for ARM

### ISSUE THREAD

**Issue by hb0nd** [flathub/com.jetpackduba.Gitnuro#5]
Continuing from https://github.com/JetpackDuba/Gitnuro/issues/85
It'd be good to provide a package for ARM devices

**Comment by JetpackDuba** [comment]
Thanks for the report, I'll investigate how flatpak manages diferent architectures.

It may also require cross compiling of some native libraries for the next release of Gitnuro, I'll have to test.

Would you like to help me testing the flatpak release? I can try to build a beta release next weekend.

**Comment by Ferenc-** [comment]
If by ARM you mean `aarch64` then it is already packaged and available on flathub.
Although it immediately crashed on the the first `aarch64` HW, that I have tried.
In the rather long exception trace, I think this was the most relevant part:
`Cannot find libskiko-linux-arm64.so.sha256, proper native dependency missing.`

**Comment by JetpackDuba** [comment]
Yeah, thanks!

I'll have to add the dependency to the final JAR.

**Comment by JetpackDuba** [comment]
@endim8 can you please try if the JAR from Gitnuro's release works as expected on ARM? I've included the dependency but I can't test it as I don't have an arm device.

https://github.com/JetpackDuba/Gitnuro/releases/download/v1.2.0/Gitnuro-linux-1.2.0.jar

**Comment by hb0nd** [comment]
> @endim8 can you please try if the JAR from Gitnuro's release works as expected on ARM?

Thank you! unfortunately, I don't have an ARM device either now... @Ferenc- are you able to test?

**Comment by Ferenc-** [comment]
> > @endim8 can you please try if the JAR from Gitnuro's release works as expected on ARM?
> 
> Thank you! unfortunately, I don't have an ARM device either now... @Ferenc- are you able to test?

I have only tested the most basic functionalities after startup, and it starts up without a crash.
There is an exception I have seen in the logs, which most probably has nothing to do with `aarch64`.
A wild guess is the flatpak sandboxing permission:
````
[SKIKO] warn: Exception in draw scope
org.jetbrains.skiko.RenderException: Cannot create surface
````
So I think this new jar fixes https://github.com/JetpackDuba/Gitnuro/issues/85

**Comment by JetpackDuba** [comment]
Great! Thank you for testing :smile:

Once the release is merged and available for Flatpak, I may ask you test it if you can.

**Comment by JetpackDuba** [comment]
The release is out, can you give it a quick test if you don't mind, please @Ferenc- ?

https://flathub.org/es/apps/com.jetpackduba.Gitnuro

**Comment by Ferenc-** [comment]
The most basic functionalities, that I have tried all worked. I think this issue can be closed.

**Comment by JetpackDuba** [comment]
Thank you!
