### ISSUE TITLE
[enhancement] Request for git fetch --prune button

### ISSUE THREAD

**Issue by 31337-4554551n** [flathub/com.jetpackduba.Gitnuro#9]
The remotes origin section cloggs up with non existent branches after they've been deleted from github.
This can be cleaned in the terminal with git fetch --prune
This is a request to have a gitnuro button/option to perform this operation (for current or all repos)

**Comment by JetpackDuba** [comment]
Hey!

As this isn't a Flathub-related issue, you should create this issue in https://github.com/JetpackDuba/Gitnuro/

Aside from that, the Fetch dropdown should already do that but I think I've found a bug in the JGit library a few days ago, having some cases where it doesn't prune refs and even sometimes fails to update still existing branches.

**Comment by 31337-4554551n** [comment]
Thank you, that's done :)

Wasn't aware that it was already meant to happen-so I've put it as a bug in the other repo.
I thought regular fetch and fetch prune would be separate things. Idk why anyone would want to keep unpruned, but it's an option in command line git and not the default.. so *shrug*

**Comment by JetpackDuba** [comment]
Yeah, Gitnuro makes some assumptions and it enables some flags aren't enabled by default in Git CLI for specific features such as this one.

Thanks for opening a new issue!
